### PR TITLE
Promises, CoffeeLint and Travis

### PR DESCRIPTION
**Pull request by ldez**
- add CoffeeLint support :coffee: 
- add [Travis CI](https://travis-ci.org/) support (please activate the build with your account) 
- refactor code to using `Promise` instead of using callback
- less code more coffee :wink:

### CODE REVIEW

**Comment by bwklein** [comment]
Thank you!

**Comment by bwklein** [comment]
@ldez What am I missing for the Travis CI build to not fail? (I am quite new to many of the technologies involved in this package.) https://travis-ci.org/bwklein/asciidoc-image-helper/builds/128127222

**Comment by ldez** [comment]
@bwklein you simply need to add tests :wink: 
I will add them in another PR.

**Comment by bwklein** [comment]
@ldez "The files are in the computer... It's so simple." :smile: 
[How am I feeling right now?](https://www.youtube.com/watch?v=H2uHBhKTSe0)

**Pull request merged**
